AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: aws-sam-ts-test
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: nodejs16.x
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs16.x
      Events:
        TestEvent:
          Type: Api 
          Properties:
            Path: /hello
            Method: get